name: CI PHPUnit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none

      - name: Install Composer dependencies
        run: composer install

      - name: Verify PHPUnit file exists
        run: ls -l vendor/bin

      - name: Fix PHPUnit permissions
        run: |
          chmod 755 vendor/bin/phpunit
          chmod +x vendor/bin/phpunit
          file vendor/bin/phpunit

      - name: Run PHPUnit tests
        run: php vendor/bin/phpunit --configuration phpunit.xml
